### ISSUE TITLE
Cannot get terminal to open

### ISSUE THREAD

**Issue by brandonleesims** [karan/atom-terminal#16]
alt - shift - T: does nothing
cmd - shift - T: 

Console Output
Uncaught TypeError: Cannot read property 'file' of undefined [~]/.atom/packages/atom-terminal/lib/atom-terminal.coffee:62

**Comment by karan** [comment]
Assuming this was fixed. If not, feel free to reply.

**Comment by doginthehat** [comment]
Still broken for me with ctrl+shift+t

Exception popup:

![screen shot 2015-02-25 at 13 45 04](https://cloud.githubusercontent.com/assets/843366/6364013/8e98f550-bcf4-11e4-8321-d424de82fb20.png)
